src/Entity/Review.php
<?php
namespace App\Entity;



use App\Repository\ReviewRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReviewRepository::class)]
class Review
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\Column]
    private ?int $rating = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'review_user_id')]
    private ?User $user_id = null;

    #[ORM\ManyToOne(inversedBy: 'review_restaurant_id')]
    private ?Restaurant $restaurant_id = null;

    #[ORM\OneToMany(mappedBy: 'review_answer_id', targetEntity: Review::class)]
    private Collection $review_answer;

    public function __construct()
    {
        $this->review_answer = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getRestaurantId(): ?Restaurant
    {
        return $this->restaurant_id;
    }

    public function setRestaurantId(?Restaurant $restaurant_id): self
    {
        $this->restaurant_id = $restaurant_id;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviewAnswer(): Collection
    {
        return $this->review_answer;
    }

    public function addReviewAnswer(Review $reviewAnswer): self
    {
        if (!$this->review_answer->contains($reviewAnswer)) {
            $this->review_answer->add($reviewAnswer);
            $reviewAnswer->setReviewId($this);
        }

        return $this;
    }

    public function removeReviewAnswer(Review $reviewAnswer): self
    {
        if ($this->review_answer->removeElement($reviewAnswer)) {
            // set the owning side to null (unless already changed)
            if ($reviewAnswer->getReviewId() === $this) {
                $reviewAnswer->setReviewId(null);
            }
        }

        return $this;
    }
}

src/Controller/CRUDReviewController.php
<?php

namespace App\Controller;

use App\Entity\Review;
use App\Form\ReviewType;
use App\Repository\ReviewRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/CRUDreview')]
class CRUDReviewController extends AbstractController
{
    #[Route('/', name: 'app_c_r_u_d_review_index', methods: ['GET'])]
    public function index(ReviewRepository $reviewRepository): Response
    {
        return $this->render('crud_review/index.html.twig', [
            'reviews' => $reviewRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_c_r_u_d_review_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReviewRepository $reviewRepository): Response
    {
        $review = new Review();
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reviewRepository->save($review, true);

            return $this->redirectToRoute('app_c_r_u_d_review_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('crud_review/new.html.twig', [
            'review' => $review,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_c_r_u_d_review_show', methods: ['GET'])]
    public function show(Review $review): Response
    {
        return $this->render('crud_review/show.html.twig', [
            'review' => $review,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_c_r_u_d_review_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Review $review, ReviewRepository $reviewRepository): Response
    {
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reviewRepository->save($review, true);

            return $this->redirectToRoute('app_c_r_u_d_review_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('crud_review/edit.html.twig', [
            'review' => $review,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_c_r_u_d_review_delete', methods: ['POST'])]
    public function delete(Request $request, Review $review, ReviewRepository $reviewRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$review->getId(), $request->request->get('_token'))) {
            $reviewRepository->remove($review, true);
        }

        return $this->redirectToRoute('app_c_r_u_d_review_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/crud_review/_delete_form.html.twig
<form method="post" action="{{ path('app_c_r_u_d_review_delete', {'id': review.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ review.id) }}">
    <button class="btn">Delete</button>
</form>

templates/crud_review/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/crud_review/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Review{% endblock %}

{% block body %}
    <h1>Edit Review</h1>

    {{ include('crud_review/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_c_r_u_d_review_index') }}">back to list</a>

    {{ include('crud_review/_delete_form.html.twig') }}
{% endblock %}

templates/crud_review/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Review index{% endblock %}

{% block body %}
    <h1>Review index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Message</th>
                <th>Rating</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for review in reviews %}
            <tr>
                <td>{{ review.id }}</td>
                <td>{{ review.message }}</td>
                <td>{{ review.rating }}</td>
                <td>{{ review.createdAt ? review.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_c_r_u_d_review_show', {'id': review.id}) }}">show</a>
                    <a href="{{ path('app_c_r_u_d_review_edit', {'id': review.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_c_r_u_d_review_new') }}">Create new</a>
{% endblock %}

templates/crud_review/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Review{% endblock %}

{% block body %}
    <h1>Create new Review</h1>

    {{ include('crud_review/_form.html.twig') }}

    <a href="{{ path('app_c_r_u_d_review_index') }}">back to list</a>
{% endblock %}

templates/crud_review/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Review{% endblock %}

{% block body %}
    <h1>Review</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ review.id }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ review.message }}</td>
            </tr>
            <tr>
                <th>Rating</th>
                <td>{{ review.rating }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ review.createdAt ? review.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_c_r_u_d_review_index') }}">back to list</a>

    <a href="{{ path('app_c_r_u_d_review_edit', {'id': review.id}) }}">edit</a>

    {{ include('crud_review/_delete_form.html.twig') }}
{% endblock %}